_type: export
__export_format: 4
__export_date: 2019-11-01T01:59:00.045Z
__export_source: insomnia.desktop.app:v7.0.1
resources:
  - _id: req_f4d511c3d0ae4f5c9dcc4b3fc4c9376b
    authentication: {}
    body:
      mimeType: application/x-www-form-urlencoded
      params:
        - id: pair_9a64df83d66a495289cd5400bbd0da4c
          name: grant_type
          value: password
        - id: pair_c3eae29068ca433f9ee8bd1315da3ae6
          name: client_id
          value: 44b00655-5178-4a87-91d1-9e0e979cb8f9
        - id: pair_6e28770610204dd2baa0f93e941c82c6
          name: client_secret
          value: 12$Oliveira4
        - id: pair_9a9729584e7d45f1bb039afaec9f5000
          name: username
          value: gatsby_user
        - id: pair_f524bce472474904ae8897b2bd4b5e0b
          name: password
          value: 12$Oliveira4
    created: 1572569907212
    description: ""
    headers:
      - id: pair_79df7e5a8f6f4ae7aefc0cdb25707726
        name: Content-Type
        value: application/x-www-form-urlencoded
    isPrivate: false
    metaSortKey: -1572569907212
    method: POST
    modified: 1572572342587
    name: Authenticate
    parameters: []
    parentId: fld_05bda90d33eb48d1a8289bd652dedf6e
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: http://cashmeserver.lndo.site/oauth/token
    _type: request
  - _id: fld_05bda90d33eb48d1a8289bd652dedf6e
    created: 1572572328741
    description: ""
    environment: {}
    environmentPropertyOrder: null
    metaSortKey: -1572572328741
    modified: 1572572328741
    name: User
    parentId: wrk_21c7f51157ec44ed9d1c52ca7be60ab3
    _type: request_group
  - _id: wrk_21c7f51157ec44ed9d1c52ca7be60ab3
    created: 1572569887556
    description: ""
    modified: 1572569887556
    name: CashMe Drupal
    parentId: null
    _type: workspace
  - _id: req_608c9826485b4c8ea371645ff4ee7f23
    authentication: {}
    body:
      mimeType: application/x-www-form-urlencoded
      params:
        - id: pair_9a64df83d66a495289cd5400bbd0da4c
          name: grant_type
          value: refresh_token
        - id: pair_c3eae29068ca433f9ee8bd1315da3ae6
          name: client_id
          value: 44b00655-5178-4a87-91d1-9e0e979cb8f9
        - id: pair_f524bce472474904ae8897b2bd4b5e0b
          name: client_secret
          value: 12$Oliveira4
        - id: pair_0848823b50ae4682a39d5f07f557d416
          name: refresh_token
          value: def5020083931163a47d95d74d3abf03b4c2715b3a8f65340393fe1352023cb274f6dd89c1127505aecc72ce02919df25780b50abe5e2111efa77b6dbdd52ba61b932c80d4b6354c7ce205a03ee3e6d7c6b860a21e7766ba214714b016d3a77992581491a853d587114130d1666519edf848a056560406d3a096d07c853fd0a729f1fa8dbc43ca2db8afa20b5076df411eafcfbfb1e7982e036694bc5d0267a6ee176fbc98d46c2e7237770ee5e036d53908ccfb6fd0eb13895d91d3459c3a4c79942606165fc0fe9ebf72abe8c47731c121fffddc79fa114fbaabb9a4c69b8429ffea5a47f3172bd3e7dbbf0a804bd18ffecfb8d29219efb4c76c703650d1cd4a4f751038b6062e3c8e17209826241e648a8cc087488f3bc7060c5cf44b4bd5cf56b0c2a156e71c4c1360198b6d34beb8a616384bd918ab7ed321e929562d1d10ae96cc23c27d67473785e88f0ff1e212172a73e102f1237463446e71e997a4bfb8acfa0c83d8318004c9f1b96243acf0df8a82fb8e23bac1a16e5c4c928ff787fdf911db70074abc410f170e856191a3825eb13b23b11fa0c2a0d59354049457f565e6
    created: 1572572790981
    description: ""
    headers:
      - id: pair_79df7e5a8f6f4ae7aefc0cdb25707726
        name: Content-Type
        value: application/x-www-form-urlencoded
    isPrivate: false
    metaSortKey: -1571529047417.5
    method: POST
    modified: 1572572912796
    name: Refresh Token
    parameters: []
    parentId: fld_05bda90d33eb48d1a8289bd652dedf6e
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: http://cashmeserver.lndo.site/oauth/token
    _type: request
  - _id: req_60b1b185cf3c4f3a845a34ddee8a1a52
    authentication:
      token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjU4NGYyOTE1NmFhZDEwYjAwOTQyYWRhNzAzZDc2ZTAwZjRjNWU4NGQ2NTk2YzZhODkyNTgzYmU0NTExMTE2M2ExZGY3N2MwYzg2ZWUwYzBlIn0.eyJhdWQiOiI0NGIwMDY1NS01MTc4LTRhODctOTFkMS05ZTBlOTc5Y2I4ZjkiLCJqdGkiOiI1ODRmMjkxNTZhYWQxMGIwMDk0MmFkYTcwM2Q3NmUwMGY0YzVlODRkNjU5NmM2YTg5MjU4M2JlNDUxMTExNjNhMWRmNzdjMGM4NmVlMGMwZSIsImlhdCI6MTU3MjU3MzQ4MiwibmJmIjoxNTcyNTczNDgyLCJleHAiOjE1NzI1NzM3ODIsInN1YiI6IjI0Iiwic2NvcGVzIjpbImF1dGhlbnRpY2F0ZWQiLCJnYXRzYnlfcm9sZSJdfQ.oIoia519TNo2j0_7Li3Z8yD6z6HSoJ5FAE4Znt2yQ6m3SyTT23LnomQ3Q9MB9lutJj528rcWkWlwtI4oNpkd9d1WrCdYvyrjhtoSSyCyo2kWeSn7PhZipb9CRRiQMGPUj8_MT2K50O2PoLPiFQiPyzRHiR2L8hL6g3QuMCR-SZp_Q5LdWAYQv-M7r0MAku7JzK4dC18eIqdHPApYzyykMEf5trkW5MeyeZsd1MIWejXC37mlsu9gfDyRSrKhrT90RzZxKW7JVX4Ap7yB_YAccg6Qgteoe7oEICDSReJuOpUC9SZQ_6kTJUeQa8-PyLzgrjeu02iBBdAq1k5tzSIBjfFw6i-ume3x2V4zA9LqmfKjg-FXli092TleBaf9XDaQWNETFqfGzh9z795D-TuZIA7jkTHW2jyOiAciVKPUvcigLd4CWhRm2gE8SbGJPzlH3Jp6TsN3ZRTwEGtFSxf8_jHfHT8SpHcEqJjBgV1_pIRMxwnaaXFbe1xVO9WUK69RqLIi62kGfjAd9o6CJXo_3w78MLJhf35PtzDaynh7-gioOMlcnx6uNtoE2wgJ-o3VDLjeHenpFSJQ7d92pDllOTss6m8ywp7Is8WCT5f6pKt_fXJ4WMNlyXqqy_DtTL7l_xBhVQ4tCwuD4PcSgyOWRhNm_JnVQuO7YO5sB_jWO4Y
      type: bearer
    body: {}
    created: 1572573154945
    description: ""
    headers: []
    isPrivate: false
    metaSortKey: -1571008617520.25
    method: GET
    modified: 1572573508361
    name: Debug Oauth
    parameters: []
    parentId: fld_05bda90d33eb48d1a8289bd652dedf6e
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: http://cashmeserver.lndo.site/oauth/debug?_format=json
    _type: request
  - _id: env_3578718022acf59bf1ab71c9051e9c5625f570b1
    color: null
    created: 1572569888186
    data: {}
    dataPropertyOrder: null
    isPrivate: false
    metaSortKey: 1572569888186
    modified: 1572569888186
    name: Base Environment
    parentId: wrk_21c7f51157ec44ed9d1c52ca7be60ab3
    _type: environment
  - _id: jar_3578718022acf59bf1ab71c9051e9c5625f570b1
    cookies:
      - creation: 2019-11-01T01:53:49.556Z
        domain: cashmeserver.lndo.site
        expires: 2019-11-24T05:27:09.000Z
        hostOnly: false
        httpOnly: true
        id: "023938891692215192"
        key: SESS34c4d6bc204ed6a4dc53af92e715cede
        lastAccessed: 2019-11-01T01:53:49.556Z
        maxAge: 2000000
        path: /
        value: xw8X25WlPaHY7g8f6UCgXy7dygpTR5iAP-cIxWIiVwM
    created: 1572569888200
    modified: 1572573229558
    name: Default Jar
    parentId: wrk_21c7f51157ec44ed9d1c52ca7be60ab3
    _type: cookie_jar
