name: cashmeclient
proxy:
  appserver:
    - cashmeclient.lndo.site
services:
  appserver:
    type: node:10
    command: "yarn dev --hostname 0.0.0.0 --port 80"
    install_dependencies_as_me:
      - yarn install
tooling:
  yarn:
    service: appserver
  npm:
    service: appserver
  node:
    service: appserver
  next:
    cmd: /app/node_modules/.bin/next
    service: appserver
