name: cash-me
recipe: drupal8
config:
  php: "7.2"
  webroot: web
  conf:
    php: .lando/php.ini
events:
  post-install:
    - appserver: cd $LANDO_WEBROOT && drush si --db-url=mysql://drupal8:drupal8@database:3306/drupal8 --site-name='CashMe - Contenta CMS' --site-mail='admin@example.com' --account-mail='admin@example.com' --account-name='admin' --account-pass='admin' --yes
  post-devel:
    - appserver: cd $LANDO_WEBROOT && drupal site:mode dev
services:
  appserver:
    build:
      - "cd $LANDO_MOUNT && composer create-project contentacms/contenta-jsonapi-project . --stability dev --no-interaction"
tooling:
  install:
    description: Install Application
    cmd: true
    service: appserver
  devel:
    description: Enable devel systems
    cmd: true
    service: appserver
