name: contentacms
# https://docs.devwithlando.io/tutorials/drupal8.html
recipe: drupal8

# Add some default configuration for the recipe here. Which will be passed to all the services within the recipe.
# https://docs.devwithlando.io/recipes/drupal8.html
config:
  # Set the webroot dir.
  webroot: contentacms/web
  # Enable xdebug autostart for CLI debugging.
  xdebug: true

# We can add additional services here or even override some configuration.
services:
  appserver:
    run:
      - 'bash $LANDO_MOUNT/config/init.sh'
    overrides:
      services:
        environment:
          # Enable PHPStorm XDebug with CLI.
          PHP_IDE_CONFIG: "serverName=appserver"
          # Set the Mink webdriver args.
          MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", null, "http://host.docker.internal:4444/wd/hub"]'
        volumes:
            # Fix linux docker host.docker.internal resolving.
          - '$LANDO_APP_ROOT/config/linux-hosts.sh:/scripts/linux-hosts.sh'
  database:
    # Add a static db port for easy bookmarking and access through SQL clients.
    portforward: 33006

# This will add some tools from the containers to the command line of your OS.
# https://docs.devwithlando.io/config/tooling.html
tooling:
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"
    cmd: "/app/contentacms/vendor/bin/phpunit --debug --configuration /app/contentacms/web/core/phpunit.xml --printer=\\Drupal\\Tests\\Listeners\\HtmlOutputPrinter"
  drush:
    cmd: "/app/contentacms/vendor/bin/drush --root=/app/contentacms/web"
  drupal:
    cmd: "/app/contentacms/vendor/bin/drupal --root=/app/contentacms/web"
